#ifndef BCM2837_SYSTIMER_REGISTER_MAPPING_H
#define BCM2837_SYSTIMER_REGISTER_MAPPING_H

#define SYSTIMER_BASE_ADDR 0x3F003000

#define SYSTIMER_MAPPING_SIZE_BYTES 28
#define SYSTIMER_MAPPING_SIZE_UINT 7

#define SYSTIMER_CTRL_STATUS_UINTP_POS 0
#define SYSTIMER_COUNTER_L32_UINTP_POS 1
#define SYSTIMER_COUNTER_H32_UINTP_POS 2
#define SYSTIMER_COMP0_UINTP_POS 3
#define SYSTIMER_COMP1_UINTP_POS 4
#define SYSTIMER_COMP2_UINTP_POS 5
#define SYSTIMER_COMP3_UINTP_POS 6

#endif
