#ifndef BCM2837_ARMTIMER_REGISTER_MAPPING_H
#define BCM2837_ARMTIMER_REGISTER_MAPPING_H

//#define ARMTIMER_BASE_ADDR 0x3F00B000
#define ARMTIMER_BASE_ADDR 0x3F00B400

#define ARMTIMER_MAPPING_SIZE_BYTES 36
#define ARMTIMER_MAPPING_SIZE_UINT 9

#define ARMTIMER_LOAD_UINTP_POS 0
#define ARMTIMER_VALUE_UINTP_POS 1
#define ARMTIMER_CTRL_UINTP_POS 2
#define ARMTIMER_INTR_CLEAR_UINTP_POS 3
#define ARMTIMER_RAW_INTR_UINTP_POS 4
#define ARMTIMER_MASKED_INTR_UINTP_POS 5
#define ARMTIMER_RELOAD_UINTP_POS 6
#define ARMTIMER_PREDIV_UINTP_POS 7
#define ARMTIMER_COUNTER_UINTP_POS 8

#endif
